---
- hosts: localhost
  become: true
  pre_tasks:
    - name: Update repositories
      dnf: update_cache=yes
      changed_when: false

  tasks:
    - name: Instalar paquetes
      include_tasks: tasks/packages.yml
      