- name: Add flathub flatpak repository remote to the user installation
  community.general.flatpak_remote: 
    name: flathub
    flatpakrepo_url: 'https://flathub.org/repo/flathub.flatpakrepo'
    state: present
- name: Deploy flatpak packages
  community.general.flatpak:
    name:
    - org.videolan.VLC
    state: present