- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install multiple packages
  community.general.flatpak:
    name:
      - com.yacreader.YACReader
      - com.anydesk.Anydesk
      - org.telegram.desktop
      - org.onlyoffice.desktopeditors
      - org.nickvision.tubeconverter
      - org.keepassxc.KeePassXC
      - org.gnome.World.Secrets
      - org.gnome.Weather
      - org.gnome.Shotwell
      - org.gnome.Extensions
      - org.filezillaproject.Filezilla
      - org.audacityteam.Audacity
      - no.mifi.losslesscut 
      - net.lutris.Lutris
      - io.mpv.Mpv
      - io.gitlab.theevilskeleton.Upscaler
      - io.gitlab.adhami3310.Impression
      - io.github.giantpinkrobots.varia
      - com.transmissionbt.Transmission 
      - com.spotify.Client
      - com.github.jeromerobert.pdfarranger
      - com.calibre_ebook.calibre

