- name: Update RPM repositories
  become: true
  dnf: update_cache=yes
  changed_when: false

- name: Deploy RPM packages
  become: true
  dnf: name={{ item }}
  with_items:
    - htop
    - mc
    - byobu
    - gnome-tweaks
    - oci-cli
    - autorestic
    - restic
    - fastfetch
    - zsh-syntax-highlighting
    - zsh-autosuggestions
    - zsh
    - vim-enhanced
    - bat
    - zoxide